### ISSUE TITLE
[BUG] matRad does not recognize DICOM files

### ISSUE THREAD

**Issue by pietemma** [e0404/matRad#553] opened 2022-04-15 07:28 UTC
hello,i cant load dicom data, GUI brings a pop up which states no DICOM files found in patient directory. i need help. I am new to matRad
Output argument "patientList" (and possibly others) not assigned a value in the execution with
"matRad_scanDicomImportFolder" function.

Error in matRad_importDicomGUI>scan (line 117)
[fileList, patient_listbox] = matRad_scanDicomImportFolder(get(handles.dir_path_field,'String'));

Error in matRad_importDicomGUI>browse_button_Callback (line 113)
    scan(hObject, eventdata, handles)

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRad_importDicomGUI (line 53)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRad_importDicomGUI('browse_button_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating UIControl Callback.

**Comment by wahln** [comment] 2022-04-19 12:12
First of all, there's a reason why we have issue templates...
Because the only thing I am getting from this error description is that it does not find dcm-files in that folder. 
- What files are present in the folder you are trying to process? Is it CT files, RTStruct, RTplan all ending with *.dcm
- What's your version of Matlab?

Maybe try running matlab's dicominfo from the command line on these files to see if Matlab itself identifies them as valid DICOM files.

**Comment by pietemma** [comment] 2022-05-03 09:49
the version of matlab is R2021b, the matlab's dicominfo works and i can view the image. The files are .dcm from a wiki repository.
![Capture](https://user-images.githubusercontent.com/102134265/166433968-70beae66-307d-42d3-8487-c88ae8096158.JPG)

**Comment by wahln** [comment] 2022-05-03 09:54
The error may appear when you have not selected / highlighted a CT series for import. Could you maybe show a screenshot of the DICOM import windows before hitting the "import" button?

**Comment by pietemma** [comment] 2022-05-03 09:58
![image](https://user-images.githubusercontent.com/102134265/166435110-ac9892e2-2534-4776-8b38-cfe4d011d280.png)

**Comment by wahln** [comment] 2022-05-03 10:12
matRad can not find a CT. Are you trying to import an MRI (as suggested by the folder name)? matRad's dicom import currently does not support MRI data, but I guess it could be extended to support it. What exactly do you want to do with the MRI in matRad?

**Comment by wahln** [comment] 2022-08-11 12:17
Since there's no more interaction here and I could not reproduce a bug, I will close this issue.

**Closed by wahln** 2022-08-11 12:17 UTC
Labels: bug
