### ISSUE TITLE
load .mat Error

### ISSUE THREAD

**Issue by linekrause** [e0404/matRad#350] opened 2019-05-15 11:01 UTC
I have tried to load .mat data in matRad-master but it did not work. I also tried this with matRad-dev and others. Has someone an idea?
This is what matRad says:

>> matRadGUI
Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more
information, click here. 
Warning: 'slider' control cannot have a 'Value' outside of 'Min'-'Max' range
Control will not be rendered until all of its parameter values are valid 
> In matRadGUI>UpdatePlot (line 851)
  In matRadGUI>reloadGUI (line 350)
  In matRadGUI>btnLoadMat_Callback (line 514)
  In gui_mainfcn (line 95)
  In matRadGUI (line 83)
  In matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRadGUI('btnLoadMat_Callback',hObject,eventdata,guidata(hObject)) 
Subscript indices must either be real positive integers or logicals.

Error in matRad_plotCtSlice (line 60)
    ct_rgb = ind2rgb(uint8(cMapScale*(squeeze((ctCube{cubeIdx}(:,:,slice)-window(1))/(window(2) - window(1))))),cMap);

Error in matRadGUI>UpdatePlot (line 964)
        [AxesHandlesCT_Dose(end+1),~,handles.dispWindow{ctIx,1}] =
        matRad_plotCtSlice(handles.axesFig,plotCtCube,1,plane,slice,ctMap,handles.dispWindow{ctIx,1});

Error in matRadGUI>reloadGUI (line 350)
UpdatePlot(handles)

Error in matRadGUI>btnLoadMat_Callback (line 514)
    handles = reloadGUI(hObject, handles, ct, cst);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in matRadGUI (line 83)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRadGUI('btnLoadMat_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback

**Comment by markbangert** [comment] 2019-05-15 11:23
What kind of data is stored in your mat file? Is this one of the example
data sets or something that you generated via the dicom import or did you
hack something yourself? Are you able to share the data with us so we can
have a look?

linekrause <notifications@github.com> schrieb am Mi., 15. Mai 2019, 13:01:

**Comment by linekrause** [comment] 2019-05-16 11:31
I have tried it with a generated data via dicom import.
The .mat data and the used .dicom data are in the following link
https://www.dropbox.com/sh/6d5de043np9qkuh/AABOAQGw9Qd_lGYGfMxE8t8ca?dl=0

thank you for your help

**Comment by wahln** [comment] 2019-05-17 12:30
First @linekrause 
Thanks for the data,
indeed it seemed like you found a bug, which is kind of also good news.
The problem is that based on the data there is no isoCenter automatically found. Due to the isocenter then being [0 0 0], the GUI assigns the default slice 0, which does not exist and the loading fails.
A workaround for now would be to 

1. try to load the data once (fails as you describe)
2. Use the GUI to manually assign a sensible isocenter like 190 190 152 and then click refresh, or use the command line to set pln.propStf.isoCenter = [190 190 152] and then click refresh in the GUI.

Let me know if this works for you!

Now @markbangert @becker89,
I keep this issue open until we fix that bug, at the moment I am not sure at which points in the code we need to fix this.  what do you think, is the missing pln a problem that stems from a bug in the DICOM import and/or should we put a safeguard into the setPln when loading of the isocenter such that the slice cannot be set to 0 or something else? I think the problem is also that there is no real target so the automatic finding of the isoCenter fails.

**Comment by markbangert** [comment] 2019-05-18 06:11
I figure we should try to make the visualization more independent of an
isocenter being set, i.e. GUI functionality must be preserved also if there
is no isocenter. Do you currently have a knowlegable Hiwi that could do
this? I ran into similar issues with research data already a couple of
times...

**Comment by markbangert** [comment] 2019-05-19 19:12
@linekrause have you figured out how to load the data or should I prepare a *mat file for you?

Cheers / Mark

**Comment by linekrause** [comment] 2019-05-20 13:45
@markbangert I will try it in the next days and if it doesn't work, i would ask for your help again

Thank you for your help!

**Comment by markbangert** [comment] 2019-05-20 20:08
great! any progress on your end with the kernels? I wanted to look into it again this weekend but did not find the time to do so...

**Comment by linekrause** [comment] 2019-05-23 12:23
@markbangert it was possible to open the plan with a workaround. But the recalculation doesn't work.
We will work with the version of matrad-dev from 15th jan (https://github.com/e0404/matRad/tree/9904c32fec7ddc1c878c1e057d97378d06938687). The upload, the real isocenter from the .dicom file shwos up and the recalc works.

**Comment by markbangert** [comment] 2019-05-23 20:51
I am not quite sure I understand everything...

If you use the current dev branch, then you can run the import but you
cannot run recalc?
If you use the version from Jan 15 then you can run the import and run
recalc?

**Comment by markbangert** [comment] 2019-06-16 20:18
@linekrause I will close this issue now. please let me know if we should open it again...

**Closed by markbangert** 2019-06-16 20:18 UTC
