### ISSUE TITLE
build ipopt mex

### ISSUE THREAD

**Issue by P705** [e0404/matRad#434] opened 2020-08-01 15:42 UTC
Hi Mark
I try to compile Ipopt with minGW but below error was appeared. 
You compile Ipopt with VS, can explain how to do this work in VS.
![1](https://user-images.githubusercontent.com/57658660/89105085-6029e380-d433-11ea-915f-d739768578f3.JPG)

**Comment by markbangert** [comment] 2020-08-02 06:25
@wahln is the ipopt compile god... Niklas, do you have any recommendations?

**Comment by wahln** [comment] 2020-08-02 22:49
It's quite difficult with VS and requires a lot of workarounds which are too complicated to explain right now.... I don't know why you want to recompile the Ipopt-mex for Matlab in the first place, is there an imcompatibility issue with R2015b now? There was some problem with R2020 and the mex interface that's why we recompiled it... consider using an older ipopt binary or something like that.

**Comment by P705** [comment] 2020-08-03 13:15
I wanna use ipopt in a matlab dll. a matlab code deploy to .net. When the .net code run with matlab dll, ipopt do not work and code crash without any error. I think may be the ipopt do not compile correctly or maybe mingw do not support sdk compiler. I want guide me in this subject.

Sent from Yahoo Mail for iPhone


On Monday, August 3, 2020, 03:19, wahln <notifications@github.com> wrote:




It's quite difficult with VS and requires a lot of workarounds which are too complicated to explain right now.... I don't know why you want to recompile the Ipopt-mex for Matlab in the first place, is there an imcompatibility issue with R2015b now? There was some problem with R2020 and the mex interface that's why we recompiled it... consider using an older ipopt binary or something like that.

**Comment by P705** [comment] 2020-08-04 11:27
Dear Niklas
The mex file in the below link, generated for Matlab 2020 doesn't work in the Matlab 2015b.
https://github.com/e0404/matRad/blob/prepareBlaise/optimization/optimizer/ipopt.mexw64
Do you test this new mex file work correctly in Matlab 2015b?

**Comment by wahln** [comment] 2020-08-04 12:21
As I already said: I suggest to try an older ipopt mex file.  E.g. the one from the first release (Alan): https://github.com/e0404/matRad/blob/2.1.0/optimization/ipopt.mexw64 
We cannot test on every system, and Matlab does not document the mex interface in such detail that I can exactly tell you in which versions which mex file will work. And I also can not help with the deployment to .NET, since we have absolutely no experience with that and have no plans trying .NET deployment in near future. matRad is a software for research and education only and therefore deployment issues are generally of minor importance to us.

What I could help with is getting fmincon to run (regarding issue #433 ) if you tell me how exactly to reproduce the error you reported  - with fmincon, it should probably be possible to deploy since then you are not relying on the mex file for optimization.

**Comment by wahln** [comment] 2020-10-06 15:51
Since there's no further activity I am closing this issue.

**Closed by wahln** 2020-10-06 15:51 UTC
