### ISSUE TITLE
Problem with open .mat data

### ISSUE THREAD

**Issue by linekrause** [e0404/matRad#359] opened 2019-07-24 07:35 UTC
Hey,

for the following i used matRad-master:
I created a .mat data with the dicom-import and then tried to open it with Load .mat data but that was not successful. MatRad showed me the following Errors:

Has anyone an idea how to fix this?

![MatRad Error](https://user-images.githubusercontent.com/50661556/61773973-35578900-adf6-11e9-9dce-c4a175ed5967.JPG)

**Comment by markbangert** [comment] 2019-07-24 11:04
hm this looks like matRad is unable to set an isocenter automatically or
something like that. do you have any structured defined in the RTSS? can
matrad automatically label one as target structure (check th cst to find
out...)?

**Comment by mingersming** [comment] 2019-08-08 12:14
In my opinion there is a problem with the processing of the dicom objects. After using the photonKernelVal branch there are more objects in the mat-file than using master branch. In detail the pln and stf objects are missing and they lead to the behavior. I will try to spot where the loss of information happens. 
First of all I compared all function files in the dicomImport folder and there are no essential differences.

**Comment by markbangert** [comment] 2019-09-09 16:14
Is there any update on this? @wahln does it make sense to look into this or are all GUI refactoring and bug fixing efforts on hold until there is a more clear timeline on how GUI development will continue in general?

**Comment by wahln** [comment] 2019-09-09 16:18
Stuff regarding the GUI code (callbacks etc) is not a big deal. I would just rather not do layout changes within the GUI at the moment.

**Comment by markbangert** [comment] 2019-09-09 16:20
OK. @mingersming do you have a fix for this issue? Should we look into this because this is holding you back? If yes could you please send detailed instructions how we can reproduce this bug? Or should we just close this issue?

**Comment by mingersming** [comment] 2019-09-11 14:14
You can close this issue.

Some insights:
I think this happens because of an in house problem. 
There are some flipping of the DICOM spatial orientations between our CT scanner and OTP.
Curious, but with an old version (dev: branch before Feb 13, 2019 [https://github.com/e0404/matRad/commit/70112334c537dd959e9704c2308cb6eaf5d10959#diff-f672aebd96bc991505af11e8e1ba4397] ) of matRad everything works fine. After the update we had to change line 292:
https://github.com/e0404/matRad/blob/0afb76def403c063909b89fbfd76ca0ea67b2626/matRadGUI.m#L292
**ct.resolution.x -> ct.resolution.z** 

to prevent the error shown by @linekrause

**Comment by markbangert** [comment] 2019-09-11 16:03
Strange but imo the orientations with matrad should be fine right now. Will choose this issue until we run into some problems elsewhere ;)

**Comment by mingersming** [comment] 2019-09-11 17:06
One final thought, could it be that the resolution (x=y=0.7422; z=2) crashes the code. This might explain the successful debugging with the z direction.
But why works the same DICOM plan with the older GUI function?
https://github.com/e0404/matRad/blob/c77f269837af2d0102b4f6bd8269dddbe70ce9e7/matRadGUI.m#L298-L311

**Closed** 2019-09-17 21:13 UTC
