### ISSUE TITLE
recalc fails after switching machine 

### ISSUE THREAD

**Issue by mingersming** [e0404/matRad#369] opened 2019-08-27 06:00 UTC
Hi there,

after switching the (photon) machine recalc fails. The problem occurs because the bixel width in the propStf is set from 'field' to 'NaN' after changing the machine. The GUI still shows 'field'. There must be a mistake for the initial procedure.
For the first you can solve it with the command pln.propStf.bixelWidth = 'field' before pressing recalc.

**Comment by wahln** [comment] 2019-08-27 08:54
Hi, 
thanks for finding this.  I guess you changed the machine via GUI?
I think the problem is that the GUI updates the bixelWidth by parsing the entry in the textfield with str2num / str2double which parses 'field' to empty / NaN. I will take a look and this and prepare a hotfix.
Thanks again!

**Comment by mingersming** [comment] 2019-08-27 09:44
Yes, you´re right, I changed the machine via GUI.
Maybe, there should be a check of the value with ~isnan(str2double(pln.propStf.bixelwidth))?

**Comment by markbangert** [comment] 2019-09-09 16:09
Is this still open? Why is the bixelWidth set to "field" in the first place? Are you recalculating a DICOM plan?

**Comment by markbangert** [comment] 2019-09-17 21:40
You mean like this https://github.com/e0404/matRad/pull/375/files?

Unfortunately I do not have any data right now to check this...

**Comment by wahln** [comment] 2020-11-09 14:50
Will be fixed in #461 . Closing.

**Closed by wahln** 2020-11-09 14:50 UTC
Labels: bug
