### ISSUE TITLE
error occurr if i just open dao on-off flag

### ISSUE THREAD

**Issue by liq07lzucn** [e0404/matRad#421] opened 2020-05-23 05:04 UTC
When I just modify one line in matRad.m as belows,

`pln.propOpt.runDAO          = true;  % 1/true: run DAO, 0/false: don't / will be ignored for particles`

there will be error occured in 

`resultGUI = matRad_siochiLeafSequencing(resultGUI,stf,dij,5);`

I found that the num of elments in resultGUI.wUnsequenced is 1376,but numOfRaysPerBeam+offset=1386,so the error occur. Hope for the reply.

**Comment by markbangert** [comment] 2020-05-23 12:09
I just looked into your problem and I cannot reproduce your bug. Running matRad.m with pln.propOpt.runDAO = true works like a charm for me. Did you also re-run the dose calculation? This might be necessary because the number of bixels can differ between DAO and non-DAO optimizations. For non-DAO you can have less bixels because we do not have to care that we have valid dose influence information for a connected row of bixels covering a row of MLC leaves.

**Comment by wahln** [comment] 2020-08-26 10:00
Since neither @markbangert nor me can reproduce the bug and there's no further activity, I am closing this issue.

**Closed by wahln** 2020-08-26 10:00 UTC
