### ISSUE TITLE
Aspect ratio of plotSliceWrapper

### ISSUE THREAD

**Issue by Haydnspass** [e0404/matRad#206] opened 2017-10-23 14:38 UTC
I encountered a bug where axes of a figure by _plotSliceWrapper do not have the right aspect ratio. I figure it has something to do with daspect (maybe another aspect ratio)?

![capture](https://user-images.githubusercontent.com/16120273/31895034-6acba734-b810-11e7-971d-5e5464493cd0.PNG)

**Comment by markbangert** [comment] 2017-12-01 09:25
Can you post a minimum example to reproduce this error or post some instructions on how to get there?

**Comment by markbangert** [comment] 2017-12-11 23:46
@Haydnspass I just tried again but could not reproduce. Can you reiterate how you got the faulty behaviour?

**Comment by markbangert** [comment] 2017-12-20 13:05
Fixed in https://github.com/e0404/matRad/commit/20a99cdb68b7b534de48fa8812071ebc51105b35

**Closed by markbangert** 2017-12-20 13:06 UTC
