### ISSUE TITLE
Issue about calcdirect

### ISSUE THREAD

**Issue by kwwong333** [e0404/matRad#355] opened 2019-06-10 11:39 UTC
I have noticed something weird with the matRad_calcDoseDirect(ct,stf,pln,cst,weight). I have attached the following matlab code which I used to run for the error. At first, I imported the TG119 phantom and run a dose calculation with optimisation for the bixel weight vector. After that I saved the optimised weight vector (i.e., resultGUI.w) to a separate array "weight". This "weight" is then used as the input for the  matRad_calcDoseDirect(ct,stf,pln,cst,weight) to compute the dose again. 

I found that the dose computed by matRad_calcDoseDirect(ct,stf,pln,cst,weight) does not really match the one after optimisation, around 10 times much smaller. Do you have any comment on that?
`
clear; load('TG119.mat'); 
clear resultGUI; 
%% define treatment plan pln.radiationMode = 'protons'; 
pln.machine = 'Generic'; 
pln.numOfFractions = 1; 
pln.propStf.bixelWidth = 5; 
pln.propStf.gantryAngles = [0 75 359]; 
pln.propStf.couchAngles = [0 0 0]; 
pln.propStf.numOfBeams = 3; 
pln.propOpt.bioOptimization = 'const_RBExD'; 
pln.propOpt.runSequencing = false; pln.propOpt.runDAO = false; 
pln.propStf.isoCenter = ones(pln.propStf.numOfBeams,1) * matRad_getIsoCenter(cst,ct,0); 
%% generate geometrical steering information 
stf = matRad_generateStf(ct,cst,pln); 
%% perform dose calculation 
dij = matRad_calcParticleDose(ct,stf,pln,cst); 
%% perform optimization
resultGUI = matRad_fluenceOptimization(dij,cst,pln); 
%% start visualization 
matRadGUI; 
%% recalucate using the optimized weight 
weight = resultGUI.w; 
clear resultGUI; 
resultGUI = matRad_calcDoseDirect(ct,stf,pln,cst,weight); 
%% start visualization 
matRadGUI;

`

**Comment by markbangert** [comment] 2019-06-10 15:37
hi @kwwong333 , I cannot reproduce your error...

running the following script with the current master branch version of matrad

`load('TG119.mat');

%% define treatment plan 
pln.radiationMode = 'protons';
pln.machine = 'Generic';
pln.numOfFractions = 1;
pln.propStf.bixelWidth = 5;
pln.propStf.gantryAngles = [0 75 359];
pln.propStf.couchAngles = [0 0 0];
pln.propStf.numOfBeams = 3;
pln.propOpt.bioOptimization = 'const_RBExD';
pln.propOpt.runSequencing = false; pln.propOpt.runDAO = false;
pln.propStf.isoCenter = ones(pln.propStf.numOfBeams,1) * matRad_getIsoCenter(cst,ct,0);

%% generate geometrical steering information
stf = matRad_generateStf(ct,cst,pln);
%% perform dose calculation
dij = matRad_calcParticleDose(ct,stf,pln,cst);
%% perform optimization
resultGUI = matRad_fluenceOptimization(dij,cst,pln);

%% recalucate using the optimized weight
weight = resultGUI.w;
resultGUI2 = matRad_calcDoseDirect(ct,stf,pln,cst,weight);`

yields identical (up to numerical errors) results as shown below:

![image](https://user-images.githubusercontent.com/10157181/59206841-12567a00-8ba6-11e9-9ea8-0fea23f95adf.png)

Is it possible that you are using an outdated matRad version or that you have some funny data stored within your TG119.mat file?

**Comment by kwwong333** [comment] 2019-06-10 17:40
Thank you. I tried one with the current master branch and there is no error.

**Comment by markbangert** [comment] 2019-06-10 17:41
Jftr: which branch and version did you use before?

**Comment by kwwong333** [comment] 2019-06-10 21:09
I think I am using the same master branch, probably i have modified something inside the code leading to this error.

**Comment by markbangert** [comment] 2019-06-10 21:37
alright. will close this issue then. good luck with matrad :)

**Closed by markbangert** 2019-06-10 21:37 UTC
