### ISSUE TITLE
Validation script for ompMC calculation

### ISSUE THREAD

**Issue by JAMKARAN** [e0404/matRad#445] opened 2020-09-12 14:31 UTC
Hi @wahln 
for following script, I saw difference between Dose1 and Dose2.
Dose1 represent Dose Calculation of Monte Carlo (ompMC) and Dose2 represents direct analytical dose calculation. There are many differences. Regarding gamma indices, Is the Monte Carlo method validated?

```
matRad_rc; 

%% Create a phantom for validation (5 cm depth for 5x5cm^2 field has 1Gy dose)
ct.resolution.x = 4;
ct.resolution.y = 4;
ct.resolution.z = 4;
ct.numOfCtScen  = 1;

xDim = 100;
yDim = 100;
zDim = 100;

ct.cubeDim      = [yDim xDim zDim]; 
 
% create an ct image series with zeros - it will be filled later
ct.cubeHU{1} = ones(ct.cubeDim) * -1000; % assign HU of Air

ixOAR = 1;
ixPTV = 2;
ixDos = 3;

cst = cell(3,6);

% define general VOI properties
cst{ixOAR,1} = 0;
cst{ixOAR,2} = 'contour';
cst{ixOAR,3} = 'OAR';

cst{ixPTV,1} = 1;
cst{ixPTV,2} = 'target';
cst{ixPTV,3} = 'TARGET';

cst{ixDos,1} = 1;
cst{ixDos,2} = 'dosimetry';
cst{ixDos,3} = 'OAR';
 
% define optimization parameter for both VOIs
cst{ixOAR,5}.TissueClass = 1;
cst{ixOAR,5}.alphaX      = 0.1000;
cst{ixOAR,5}.betaX       = 0.0500;
cst{ixOAR,5}.Priority    = 2;
cst{ixOAR,5}.Visible     = 1;
cst{ixOAR,5}.visibleColor = [1 0 0];

% define objective as struct for compatibility with GNU Octave I/O
cst{ixOAR,6}{1} = struct(DoseObjectives.matRad_SquaredOverdosing(10,30));

cst{ixPTV,5}.TissueClass = 1;
cst{ixPTV,5}.alphaX      = 0.1000;
cst{ixPTV,5}.betaX       = 0.0500;
cst{ixPTV,5}.Priority    = 1;
cst{ixPTV,5}.Visible     = 1;
cst{ixPTV,5}.visibleColor = [0 1 0];

% define objective as struct for compatibility with GNU Octave I/O
cst{ixPTV,6}{1} = struct(DoseObjectives.matRad_SquaredDeviation(800,60));

cst{ixDos,5}.TissueClass = 1;
cst{ixDos,5}.alphaX      = 0.1000;
cst{ixDos,5}.betaX       = 0.0500;
cst{ixDos,5}.Priority    = 2;
cst{ixDos,5}.Visible     = 1;
cst{ixDos,5}.visibleColor = [0 0 1];
 
cubeHelper = false(ct.cubeDim);

xLowOAR  = 25;
xHighOAR = 75;
yLowOAR  = 25;
yHighOAR = 75;
zLowOAR  = 25;
zHighOAR = 75;

for x = xLowOAR:1:xHighOAR
 for y = yLowOAR:1:yHighOAR
    for z = zLowOAR:1:zHighOAR
       cubeHelper(y,x,z) = true;
    end
 end
end

ct.cubeHU{1}(cubeHelper) = 0;
cst{ixOAR,4}{1} = find(cubeHelper);

xLowPTV  = 50-6;
xHighPTV = 50+6;
yLowPTV  = 50-6;
yHighPTV = 50+6;
zLowPTV  = 50-6;
zHighPTV = 50+6;

cubeHelper = false(ct.cubeDim);

for x = xLowPTV:1:xHighPTV
 for y = yLowPTV:1:yHighPTV
    for z = zLowPTV:1:zHighPTV
       cubeHelper(y,x,z) = true;
    end
 end
end

ct.cubeHU{1}(cubeHelper) = 0;
cst{ixPTV,4}{1} = find(cubeHelper);

cubeHelper = false(ct.cubeDim);
cubeHelper(50-13,50,50) = true;
cst{ixDos,4}{1} = find(cubeHelper);

%% Pln
pln.radiationMode  = 'photons';  
pln.machine        = 'Generic';
pln.numOfFractions = 1;
pln.propOpt.bioOptimization = 'none';    
pln.propStf.gantryAngles    = 0;
pln.propStf.couchAngles     = 0;
pln.propStf.bixelWidth      = 50;
pln.propStf.numOfBeams      = numel(pln.propStf.gantryAngles);
pln.propStf.isoCenter       = ones(pln.propStf.numOfBeams,1) * matRad_getIsoCenter(cst,ct,0);
pln.propStf.isoCenter(2)    = pln.propStf.isoCenter(2) - 2;
pln.propStf.addMargin       = false;

pln.propOpt.runSequencing   = 0;
pln.propOpt.runDAO          = 0;

% dose calculation settings
pln.propDoseCalc.doseGrid.resolution.x = 4; % [mm]
pln.propDoseCalc.doseGrid.resolution.y = 4; % [mm]
pln.propDoseCalc.doseGrid.resolution.z = 4; % [mm]

pln.propMC.outputVariance = true;

ct = matRad_calcWaterEqD(ct,pln);

%% Generate Beam Geometry STF
stf = matRad_generateStf(ct,cst,pln);
stf = matRad_computeSSD(stf,ct);
matRad_cfg.dispInfo('SSD: %g\n',stf.ray(1).SSD);

%% Dose Calculation MC
dij = matRad_calcPhotonDoseMC(ct,stf,pln,cst,5e4);

%% Inverse Optimization for IMRT
resultGUI = matRad_calcCubes(ones(dij.totalNumOfBixels,1),dij);

%% Calculate direct analytical dose for comparison
resultGUI2 = matRad_calcDoseDirect(ct,stf,pln,cst,resultGUI.w);

%% Evaluate difference
matRad_compareDose(resultGUI.physicalDose,resultGUI2.physicalDose,ct,cst,[1 1 1],'on',pln,[3 3],2,'global');

%% Plot statistics
if isfield(resultGUI,'physicalDose_MCstd')
    matRad_plotSliceWrapper(axes(figure),ct,cst,1,resultGUI.physicalDose_MCstd,3,round(ct.cubeDim(3)/2));
    matRad_cfg.dispInfo('Maximum MC std = %gGy with maximum dose of %gGy\n',max(resultGUI.physicalDose_MCstd(:)),max(resultGUI.physicalDose(:)));
end
 
%% Get dose in Helper
matRad_cfg.dispInfo('Dose at 5cm WEPL: MC -> %g, SVD-PB -> %g\n',resultGUI.physicalDose(cst{ixDos,4}{1}),resultGUI2.physicalDose(cst{ixDos,4}{1}));

```

![1](https://user-images.githubusercontent.com/25560098/92997690-59aa8380-f52a-11ea-826c-67c5036741dd.JPG)
![2](https://user-images.githubusercontent.com/25560098/92997694-6038fb00-f52a-11ea-892e-17921c127913.JPG)
![3](https://user-images.githubusercontent.com/25560098/92997696-6202be80-f52a-11ea-9854-6154338b8477.JPG)
![2](https://user-images.githubusercontent.com/25560098/92997699-6333eb80-f52a-11ea-846f-0865c9fc4535.JPG)
![4](https://user-images.githubusercontent.com/25560098/92997700-6333eb80-f52a-11ea-844c-21d64af31901.JPG)
![Uploading 5.JPG…]()
![Uploading 3.JPG…]()

**Comment by wahln** [comment] 2020-09-14 09:13
For the photon Monte Carlo method, which is developed by @edoerner, the transport (i.e., the photon/electron transport) is validated against EGSnrc. However, there's no exact machine / collimator modelling, thus the dose distributions might be different (ompMC uses a point source). Also, while there seems to be some kind of absolute bias in dose, you are definetely not running enough histories to have good MC statistics.

**Comment by JAMKARAN** [comment] 2020-09-14 11:36
Thanks @wahln 

I run the script with 10 millions histories that following figures of profiles obtained. Variation of MC values are acceptable and also they have good MC statistics. 
![112](https://user-images.githubusercontent.com/25560098/93078916-8b455b00-f6a0-11ea-8ebb-7a4b8e138bd3.jpg)
@wahln @edoerner  I have some questions about ompMC that be thankful for answering the :
1.  Is it possible exact machine (with precise collimator modelling) simulated on EGSnrc (BEAMnrc) and append to ompMC? for example phase-space files or full geometry uses in source code.
2. Inside the [ompMC/spectra/](https://github.com/e0404/ompMC/tree/6ca7970683999ae8b026c06e1ad1b67757c13033/spectra) we saw so energy spectrum of specific machine as Clinac 2100 or Mohan 6MV spectrum. Is it correct I use our machine spectrum for MC transport and MC dose calculation? If No, Why?
3. @edoerner use peg4dat files for defining the material, what is pgs4form.dat?

4. Also you @edoerner use some specific phantoms (TG119.egsphant, WATER.egsphantphantoms and PROSTATE.egsphant), where is use them? In matRad_example4_photonsMC.m we load BOXPHANTOM.mat. 

5. Thanks for all developers and contributes

**Comment by edoerner** [comment] 2020-09-15 00:52
Hi @JAMKARAN, as @wahln pointed out ompMC is validated against EGSnrc. You could review the comparison in the following master Thesis of @dramirezsolano in https://repositorio.uc.cl/handle/11534/40132 (in Spanish, but you can take a look the figures in the pdf file). Maybe there is a problem with the calibration factor, we will give a look on it. Now the questions:

1. Currently it is not supported exact machine simulation or the use of phsp files. Regarding the current structure of the code the latter alternative should be achievable with a reasonable developing effort, though.
2. You are free to use your own spectrum files, but of course it should change the shape of your dose profile.
3. pgs4form.dat is used to read the default atomic form factors needed for coherent scattering angular sampling. You can get more information in the EGSnrc user manual (PIRS701)
4. egsphant files are needed only if ompMC is used outside matRad. Within matRad the .mat phantoms are adapted to be used by ompMC "on the fly", so you can change of phantom as you wish.

**Comment by JAMKARAN** [comment] 2020-09-15 18:06
@edoerner very thanks for introduction of master thesis.
Thanks you for answering. 
what's requirement for adding exact geometry into opmMC?

**Comment by wahln** [comment] 2020-09-16 10:22
It would require modification of the C source code (which is not on our immediate agenda). Having a full geometry (i.e. accelerator head & MLC) would be a quite substantial modification. As @edoerner said, phase-space files or better phase-space parameterizations would be probably more simple to add, since they only change the particle source and initial momentum distributions.

**Comment by JAMKARAN** [comment] 2020-10-05 06:09
Thanks @wahln

**Comment by wahln** [comment] 2020-10-05 08:46
Good, will close this issue now

**Comment by wahln** [comment] 2020-10-08 13:32
I wanted to reopen this issue because I just happend to look at the validation script again. When I run this script on my machine, I get (almost) perfect matching between analytical and MC-calculated dose (except for some build-up & penumbra differences). I attached the respective image and the original version of my script: [matRad_validate_photonsMC.txt](https://github.com/e0404/matRad/files/5348133/matRad_validate_photonsMC.txt) (just rename to *.m, github only allows txt). Did you use the 2.10.0 release of matRad for your computations or some older version? Could you also provide the exact console output from the computations so we can check how ompMC is initialized on your machine? 
Profiles:
![photonValidation](https://user-images.githubusercontent.com/11944339/95465130-0a197500-097b-11eb-8de3-ba8b8ccf8e10.png)
Slice and difference maps:
![photonValidationSlice](https://user-images.githubusercontent.com/11944339/95465138-0c7bcf00-097b-11eb-8317-bda3d5b81468.png)

**Comment by JAMKARAN** [comment] 2020-10-10 07:39
Hi @wahln 
Yes. I use the 2.10.0 release of matRad.
Also the outputs from the computations were attached below:

Profiles:

![prof](https://user-images.githubusercontent.com/25560098/95648599-6698a380-0ae5-11eb-9779-03eed335cdbb.jpg)

Slice and difference maps:

![yx](https://user-images.githubusercontent.com/25560098/95648600-6ac4c100-0ae5-11eb-9187-84fb6e14fe62.jpg)


But when I changed `absCalibrationFactor = 3.47098 * 1e10; %Approximate! ` to  `absCalibrationFactor = 4.390 * 1e10;  ` (line 279 of matRad_calcPhotonDoseMC.m), suitable matching between analytical and MC-calculated dose observed:

Profiles:

![prof2](https://user-images.githubusercontent.com/25560098/95649135-d9574e00-0ae8-11eb-8c17-721678384849.jpg)

Slice and difference maps:
![yx2](https://user-images.githubusercontent.com/25560098/95649153-ef650e80-0ae8-11eb-8ab2-d3a82b22f417.jpg)

**Comment by wahln** [comment] 2020-10-12 08:56
Since I do not see the same behavior, it would be helpful to have the output/log from the Matlab command line that is given by ompMC before calculation to isolate the differences between both our runs. It might help to isolate the source of the inconsistent behavior. Also, do you change any parameters like bixelWidth? What machine are you running on?

**Comment by JAMKARAN** [comment] 2020-10-14 06:35
Hi @wahln 
while I used another spectrum and modified generic machine, I had not paid attention to it. When you remarked that I used the matrad generic machine and mohan6 energy spectrum, your correct results obtained.
Many thanks to @wahln

**Comment by wahln** [comment] 2020-10-14 07:08
Perfect. Closing this now.

**Closed by wahln** 2020-10-14 07:08 UTC
Labels: question

**Comment by JAMKARAN** [comment] 2020-10-21 14:37
Hi again @wahln 
Can the script be used for other phantoms? in fact, this script for other phantoms has been validated or compared by an analytical (SVD) algorithm. I used your script for BOXPHANTOM.mat ([here](https://github.com/e0404/matRad/blob/master/phantoms/BOXPHANTOM.mat)) and observed the following results:

**Comment by wahln** [comment] 2020-10-21 15:25
In principle you can try to recreate the calibration geometry on the other phantoms. However, the large field size (50mm x 50mm) will on the one hand reveal limitations of the SVD algorithm, especially when the impinging surface is not flat (since the convolution kernels are precomputed for one SSD), on the other hand the simple source modeling of the MC algorithm will give you different penumbras (notice that you observe the largest difference in the BOXPHANTOM at the field edges). Also different resolutions will change the outcome of the gamma analysis, first because you have better resolution on the problematic penumbra and second because with better resolution the MC statistical accuracy gets worse.

**Comment by JAMKARAN** [comment] 2020-10-22 08:39
Thanks @wahln @edoerner 
1. How can I recreate the calibration geometry on the other phantoms. Should the absolute calibration factor change for any phantoms?
`absCalibrationFactor = 3.47098 * 1e10 ` (line 279 in script 'matRad_calcPhotonDoseMC.m').
2. For all phantoms I use your script that write on above; with bixel width 50 mm (`pln.propStf.bixelWidth      = 50; `). Does the of pass rate of gamma indices improve by reducing this amount? which method improves dose calculation accuracy, SVD or MC? 
3. Does the accuracy of Monte Carlo method improved by decreasing bixelWidth?

**Comment by wahln** [comment] 2020-10-22 08:58
I want to point out again that we didn't aim for perfect matching of the SVD and MC in this first integration. The current MC implementation was integrated vor specific research questions that do not require perfect modeling of machine geometry. Therefore in the current implementation state, it will be near impossible to match them due to the inherent limitations in modeling machine geometry. We may look at this in near future, but now this makes it tricky to satisfyingly answer your questions... but i'll try...
1. you need to position the isocenter in a way that you have an SSD of 900mm. If you use (5cm)^2 squared fields, the calibration should be fine, but you still will see differences due to above limitations
2. probably not, but you can try out. Changing the bixelWidth / fieldWidth changes machine output etc. depending on the machine, where we again arrive at above limitations. In general, MC will be more accurate regarding photon & electron transport, but in its current state not for a specific machine. What you are going to use depends on what research you would want to do...
3.  see 2

**Comment by JAMKARAN** [comment] 2020-10-22 09:29
Dear Niklas @wahln 
Many thanks for fast and accurate reply. 
I want to evaluate accuracy of SVD method. I don't find proper documentation (or data) for evaluation of photon dose calculation (SVD method) in Wiki of matRad on github. So, I think ompMC is accurate and available for that job, I start comparing the two method (SVD and ompMC MC method) following your valuable comments.

**Comment by JAMKARAN** [comment] 2020-10-26 13:26
Hi again Niklas @wahln 
I wanna find a reliable for evaluation accuracy of your SVD method implementation on matRad; or you reveal methods to evaluated that by me.
Thanks

**Comment by JAMKARAN** [comment] 2020-10-26 13:38
Excuse me, you said "In principle you can try to recreate the calibration geometry on the other phantoms." I want to recreate the calibration geometry for one of common matRat's phantoms (for example Head&Neck.mat ([here](https://github.com/e0404/matRad/blob/master/phantoms/HEAD_AND_NECK.mat))). How can I do this?
Also,

**Comment by wahln** [comment] 2020-10-26 14:35
As I said, it is not that straightforward to evaluate the dosimetric accuracy of the SVD algorithm vs Monte Carlo with the current implementation of ompMC, since the machine modeling is not the same in both cases and there will always be an underlying bias due to that. If any, you can only produce quantitative results with the calibration geometry. The calibration geometry is given for exactly the 50x50 mm field, when the SSD is 900cm. To reproduce this geometry in other cases, you need to (1) adjust the isocenter in `pln.propStf.isoCenter` manually such that the SSD is 900cm. (2) make sure only one beamlet/bixel is present in the resulting stf. A code snippet I like to use (after `matRad_generateStf(...)`) to reduce the stf to the central ray is this:
```
rayIx = find(cellfun(@(rayPos) isequal(rayPos,[0,0,0]),{stf.ray.rayPos_bev}));
%rayIx = 1;
stf.ray = stf.ray(rayIx);
stf.numOfBixelsPerRay = 1;
stf.numOfRays = 1;
stf.totalNumOfBixels = 1;
```
The rest you need to figure out for yourself.

Something that might help you: I recently pushed an update to ompMC that now uses a virtual Gaussian photon source. We observerd that this improves modeling of the penumbra with the Monte Carlo algorithm. The current development version is on https://github.com/e0404/matRad/tree/dev_ompMC . However, I did only recompile the binaries for Windows & Linux so far, Mac will still use the old version with a point source.

**Comment by JAMKARAN** [comment] 2020-10-26 15:14
Thanks Niklas. I understood ompMC is not perfect for any phantoms.
If possible I want to know how you append a virtual Gaussian photon source on ompMC. I will be happy if you explain on script.

Last, without paying attention to ompMC, I wanna find a reliable for evaluation accuracy of your SVD method implementation on matRad. What do you suggest?

**Comment by wahln** [comment] 2020-10-26 15:28
Just use the same script with the new version in the link. Check out the file matRad_calculatePhotonDoseMC(...). The option is set automatically in line 97 & 98. The value is derived with a simple geometry estimate given SAD, SCD and the (measured) width of the penumbra at isocenter, which is now stored in the machine file.

Without any reference it is difficult to evaluate the accuracy of the algorithm. The only alternative then is to compare to measurements or the output of another treatment planning system. If you have another system or access to accelerator data, you can try to fit your own SVD kernel base data set given output factor, primary fluence, PDD curves, etc. You can find an ongoing(!) project to fit such kernels here: https://github.com/e0404/photonPencilBeamKernelCalc 

Sorry that I can't provide more guidance, but at some point it is starting to cost me as much time as it would cost you to dig into the details.

**Comment by JAMKARAN** [comment] 2020-10-26 17:47
Very thanks, Niklas. You are a perfect man and your valuable comment is very facilitator.

**Comment by chialung0811** [comment] 2021-12-20 09:14
Hello @wahln ,

Thanks for developing this useful tool kit for treatment planning research. I have a question about ImpMC. In the end of this discussion, you mentioned that OmpMC now use virtual Gaussian photon source. I also went to the source code of ompMC (thanks @edoerner ) and tried to read the content in matrad.c . However, I found that the gaussian width in OmpMC options is not called or used in the code. Is that true or my understanding is wrong? Thank you.

Jackie Chien

**Comment by wahln** [comment] 2021-12-20 13:05
Dear Jackie,

thanks! I very much appreciate that someone is taking a closer look at the photon Monte Carlo. The virtual Gaussian source is something I am to blame for and that I quite quickly hacked into the code with only short validation, and it is very much possible that there is "room for improvement", so to speak. If you see that something doesn't make sense, let me know and I see if I can fix it. Here's the information that you seek:

-  The file that was compiled into the mex interface is here: https://github.com/e0404/ompMC/blob/a8f4a673a84bca5392f2a55d52ad1cd0c4dd74db/ucodes/omc_matrad/omc_matrad.c basically, we always use omc_matrad.c in the version that is linked in the submodules to compile the mex, which is then put into the ompMC folder (the reason we have a submodule and a folder with binaries is that submodules are not included in the tar/zip source code download).
- In the file, particles are sampled from the Gaussian source here: https://github.com/e0404/ompMC/blob/a8f4a673a84bca5392f2a55d52ad1cd0c4dd74db/ucodes/omc_matrad/omc_matrad.c#L1245-L1295 
somewhere further up, you find the configuration parsing
- The source width (sigma) is computed from the penumbraFWHMatIso parameter here: https://github.com/e0404/matRad/blob/3d29b765a9a0a02a593890726102a7d9db907af7/matRad_calcPhotonDoseMC.m#L68-L69

Regarding dose calculation and MC interfaces, there is also quite some refactoring going on at the moment. If you wish for some feature, now is the time! Also feel free to start a new issue / discussion then.
