### ISSUE TITLE
Abort callback from fluence optimization not working on macOS

### ISSUE THREAD

**Issue by Haydnspass** [e0404/matRad#174] opened 2017-08-09 14:08 UTC
When one aborts fluence optimization before it converged, usually there should be a callback generating the resultGUI structure using the present optimization step. For me it does not work neither on macOS nor on the new machine (Win 10, R2017a). As far as I knnow @becker89 encountered the same issue at least on mac.

**Comment by becker89** [comment] 2017-08-09 22:11
Yes I experienced the same issue on macOS but haven't had time to investigate.

**Comment by markbangert** [comment] 2017-12-01 13:40
Anybody of the Mac Users (@becker89 & @Haydnspass ) willing to look into this before we make the next matRad release on Xmas?

**Comment by markbangert** [comment] 2018-04-04 15:14
@ahmadnish can you look into this and maybe make a pull request?

**Comment by ahmadnish** [comment] 2018-04-05 18:50
after spending the better half of the day, searching where the problem is, realized the best solution to the issue is to do nothing! 

So the code is pretty correct, and keycodes are right, however, pressing `Ctrl + c` would terminate the operation and won't let _CWkeypressCallback_ to assign a flag to _IPOPT_ solver, and this is the case for both Windows and Mac. However, "**q**" the other assigned key to abort the callback works perfectly fine in both macOS and Windows and would generate the `resultGUI` with the present optimization step. I suggest using it in such cases.

Regarding how Ctrl + c acts different in Unix-based systems comparing to Windows-based systems, read [here](https://de.mathworks.com/matlabcentral/answers/94419-why-am-i-unable-to-consistently-use-ctrl-c-to-break-out-of-an-operation-in-matlab-6-0-r12-and-late)

Regarding how Ctrl + c can be handled in Mex files read [here](https://www.advanpix.com/2016/07/02/devnotes-3-proper-handling-of-ctrl-c-in-mex-module), which I think it's too much of a hassle, using "**q**" does the job.

**Comment by markbangert** [comment] 2018-04-06 14:40
Hi Ahmad, thanks for digging into this. I would suggest we make the
following changes...

1. We take our the check for ctrl+C completely also from the
keypressfunction.
2. We should include some output on the command prompt to tell people that
they have the option to inzerrupt optimization by pressing CRTLQ - or we
make this in the window that display the objective function?! Just
something like "Press ctrl+q to terminate." will do,
3. We should rename  matRad_STRG_C_Pressed to matRad_CTRL_Q_Pressed

Can you make these changes and prepare a pull request?

Cheers / Mark

**Comment by ahmadnish** [comment] 2018-04-06 16:47
ctrl+q closes matlab while ipopt is running, and plus it is the **quit program** shortcut in Windows for some programs. So I guess we have to come up with another shortcut, any suggestions? 

I personally suggest the "q" itself, without the ctrl key.

**Comment by markbangert** [comment] 2018-04-10 10:53
This issue has been resolved by @ahmadnish in https://github.com/e0404/matRad/pull/262 with the solution of making "q" the termination callback. Thanks! Will close this issue now...

**Closed by markbangert** 2018-04-10 10:53 UTC
