### ISSUE TITLE
DICOM folder import issues

### ISSUE THREAD

**Issue by ItalianCannon** [e0404/matRad#439] opened 2020-08-25 07:11 UTC
Hello,

I would like to import a set of DICOM files into matrad (a folder contains a series of DICOM files), I can successfully load the data, but when I click the "import" button there will be errors, I tried different data from TCIA but they won't work. The errors are usually:
""""
Undefined function or variable 'selected_ctseries'.
Error in matRad_importDicomGUI>import_button_Callback (line 280)
        strcmp(handles.fileList(:,4), selected_ctseries),:);
Error in gui_mainfcn (line 95)
        feval(varargin{:});
Error in matRad_importDicomGUI (line 53)
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)matRad_importDicomGUI('import_button_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.
"""

Could you please help me on this, thanks.

**Comment by wahln** [comment] 2020-08-25 19:21
Hi,
what kind of data is in the dicom folder? ct slices? RTDose? RTStruct? RTPlan?
From looking into the code with your error message, I think the error may appear when the CT Series is not correctly identified.

**Comment by ItalianCannon** [comment] 2020-08-26 07:55
> Hi,
> what kind of data is in the dicom folder? ct slices? RTDose? RTStruct? RTPlan?
> From looking into the code with your error message, I think the error may appear when the CT Series is not correctly identified.

Thanks for the reply, I think the data is CT slices.

**Comment by wahln** [comment] 2020-08-26 09:57
OK, I managed to reproduce the exact same error with my test dataset when removing all CT slices from the folder. So either there are no DICOM CT slices in your folder, or the CT slices are not recognized as such. Unfortunately, the GUI only provides basic matRad functionality and then does not support import without CT (which can, however, be achieved with some programming from the Matlab Command Line using the appropraite matRad functions). Maybe you can provide a screenshot of the contents of the Dicom Import GUI after browsing the folder and/or a screenshot of the folder contents you are trying to import. Then I might be able to help further.

**Comment by ItalianCannon** [comment] 2020-08-26 10:21
Thanks, the DCM files can beloaded, but have problem with import, I'll also try the command lines.
![Screenshot from 2020-08-26 12-24-57](https://user-images.githubusercontent.com/62165454/91292342-a48c7300-e796-11ea-8cb4-b1a5553fc4ed.png)

**Comment by wahln** [comment] 2020-08-26 11:23
yes, seems like CT slices are present. Does the CT Box in the dicom import window show one or multiple entreis (it should show the Series Instance UID of the dicom dataset)?

**Comment by ItalianCannon** [comment] 2020-08-26 11:41
Yes, it shows 2 names '2011'.
![Screenshot from 2020-08-26 13-41-57](https://user-images.githubusercontent.com/62165454/91299310-b3c4ee00-e7a1-11ea-94b0-58f829ddfa72.png)

**Comment by wahln** [comment] 2020-08-26 11:45
Ok, then i do not fully understand why the import is not working for you / the images from TCIA. Could you give me the link to the dataset on TCIA? Then I will try to get to the bottom of this!

**Comment by ItalianCannon** [comment] 2020-08-26 11:49
I just restarted MATLAB, and things are back to normal, I guess that there are too many things in my workspace, sorry for the disturbance and thank you.

**Comment by wahln** [comment] 2020-08-26 11:55
OK. Nevertheless, thank you for the "bug report" because I found another bug when investigating your issue ;)
Will close this now

**Closed by wahln** 2020-08-26 11:55 UTC
