### ISSUE TITLE
Optimization error

### ISSUE THREAD

**Issue by adrianamaria** [e0404/matRad#94] opened 2016-08-25 20:44 UTC
Hello,

Could you please help me understand with this error means and provide, if possible, ways to overcome it?
_OptimizeCallback: Could not optimize!
Attempted to access param(2); index out of bounds because numel(param)=1;_

or

_OptimizeCallback: Could not optimize!
Dimensions of matrices being concatenated are not consistent;_

Many thanks in advance for your kind help.
Best regards,
Adriana

**Comment by markbangert** [comment] 2016-08-25 21:05
Hi Adriana,

this really looks like a bug in our code. It has to do with the internal
handling of objectives and their associated parameters (penalty and
reference dose level for example).

Could you let me know if you are using the latest matRad version from
github? Could you maybe provide a workspace for download so I can reproduce
this error?

If you want you can use matrad@dkfz.de to provide files or links to files.

Cheers / Mark

**Comment by adrianamaria** [comment] 2016-08-27 09:45
Hello Mark,

I wasn't using the lastest matRad version. It is fixed now, thank you.

Best regards

**Comment by markbangert** [comment] 2016-08-27 20:02
Good to know.

Sorry for the confusion but recently we made a couple of major changes to
the code and I am afraid that came with a couple of bugs that we get rid of
one after the other.

Thank you very much for your understanding.

Cheers / Mark

**Comment by adrianamaria** [comment] 2016-08-30 12:24
Hello,

I reopened the issue because i keep getting the same error. Please find below the link for the variables in my workspace.

https://we.tl/fMHHqttLP3 

Many thanks!
Adriana

**Comment by markbangert** [comment] 2016-08-31 19:47
I'm away from Heidelberg until October. @becker89 could you maybe have a
look or ask Alex to Check it out?! Thanks...

Am 30.08.2016 2:24 nachm. schrieb "adrianamaria" <notifications@github.com>:

**Comment by becker89** [comment] 2016-09-01 09:47
Hi Adriana,
thanks for opening this issue gain. Indeed, we have a bug in our code. The problem is that a min max mean constraint requires two input parameters, namely a min mean and a max mean parameter (e.g. 40Gy and 50Gy). Right now you have only provided one parameter which results in the error message you mentioned above "Attempted to access param(2); index out of bounds because numel(param)=1;" - This error occurs because there isn't a second parameter. And now here comes the bug - it is not possible two enter two space separated numbers in the dose column at least not in Matlab2015b. The column's datatype is defined as numeric and therefore only accepts a single value. When entering two space separated numbers "40 50", Matlab automatically sets the value to NaN because it interprets these two numbers as text . We have had this problem before. In a earlier version we defined the datatype of the dose column as text, which allowed entering "40 50" and then converted it manually to a numeric value(s) @HenningMescher . For reasons I don't know right now we changed it the dataype back to numeric. I will think about how we can solve this once and for all. Meanwhile you can use a max mean dose constraints and if you want a min mean dose for your OARs.

**Comment by markbangert** [comment] 2016-09-01 19:03
To me honest in my opinion we should discontinue support for a min max mean
constraint. Users can use two separate constraints if they want...

Am 01.09.2016 11:48 vorm. schrieb "becker89" <notifications@github.com>:

**Comment by becker89** [comment] 2016-09-01 21:52
I agree - but then I would also take out the min max mean dose constraint. As you mentioned users can define two separate objectives. Taking out the min max mean dose constraint would have the nice side effect keeping the dose column with datatype numeric (as it is now) - otherwise I think we would have to change this to text ...

**Comment by markbangert** [comment] 2016-09-02 16:58
Agreed. Take both out.

Am 01.09.2016 11:52 nachm. schrieb "becker89" <notifications@github.com>:

**Comment by markbangert** [comment] 2016-09-22 18:27
@becker89 can we close this issue? Did you make the changes to the code?

**Comment by becker89** [comment] 2016-09-23 05:38
Yes since yesterday the change is on the master branch. I am going to close this issue now

**Closed by becker89** 2016-09-23 05:38 UTC
