### ISSUE TITLE
colorbar of the matRadGUI

### ISSUE THREAD

**Issue by Phoebegit** [e0404/matRad#290] opened 2018-08-14 03:35 UTC
![image](https://user-images.githubusercontent.com/31639780/44069778-fd70335e-9fb2-11e8-9dfe-1f2a994db66a.png)

![image](https://user-images.githubusercontent.com/31639780/44069799-16bc8696-9fb3-11e8-84a4-d3cdd1eaf1c0.png)

Hi,
   there is a little problem about **colorbar** of the matRadGUI . As shown in the two pictures above,the value of the colorbar is not match with the data ploted in the figure1. In this plan, the Prescription dose is 2000cGy & the number of fractions is 10 , but int the colorbar , red represent 60Gy .
   whatever you  change the data(physicalDose),the colorbar dosen't change.
I guass because
`dose_rgb = ind2rgb(uint8(cMapScale*(dose_slice - window(1))/(window(2)-window(1))),cMap);`
'doseHandle = image('CData',dose_rgb,'Parent',axesHandle);'

3D rgb value cannot be associated with colorbar

**Comment by markbangert** [comment] 2018-08-14 04:59
Thanks for reporting this issue. Can you provide us with exact instructions
how to reproduce this error? Should we just run the boxphantom with one
photon beam and the standard objectives and constraints?

Mengya Guo <notifications@github.com> schrieb am Di., 14. Aug. 2018, 05:35:

**Comment by Phoebegit** [comment] 2018-08-14 06:41
![image](https://user-images.githubusercontent.com/31639780/44075483-86f1ae2a-9fcf-11e8-839b-1e69a89af2f5.png)


I just  run the boxphantom with one **proton** beam and the standard objectives . The Prescription dose is 2000cGy for target.
The colorbar dosen't change .

**Comment by Phoebegit** [comment] 2018-08-14 06:50
![image](https://user-images.githubusercontent.com/31639780/44075863-dfb2ddda-9fd0-11e8-89fc-ca10951d9b36.png)


When I changed the **number of fractions** from 30 to 10 and other remains the same with previous picture , the colorbar has not change since the beginning

**Comment by markbangert** [comment] 2018-08-14 08:56
I cannot reproduce your error at once. If I open the TG119 phantom and run a proton treatment plan as specified in the image below for 30 frac (note the adjusted reference dose, i.e., 60Gy, in the squared deviation objective of the target) the colorbar is correctly labeled (max at around 2Gy) and the DVH is also consistent.

![image](https://user-images.githubusercontent.com/10157181/44082042-80034da4-9fb0-11e8-8276-2621709d83fd.png)

Can you please provide STEP BY STEP instructions how to reproduce your error?

**Comment by markbangert** [comment] 2018-08-14 08:56
Are you using the latest version from the dev branch? Is this maybe only an error in the master branch?

**Comment by Phoebegit** [comment] 2018-08-14 13:13
May be the matlab version cause the issue. my matlab version is 2014b,when I use 2016b to run the code ,the colorbar is OK.

![image](https://user-images.githubusercontent.com/31639780/44093674-c655a1f2-a006-11e8-8e93-e17354489a03.png)

Thanks for your patience!

**Comment by Phoebegit** [comment] 2018-08-14 13:15
when using matlab 2014b ,the colorbar of the dev or the master is still not ok.

**Comment by markbangert** [comment] 2018-08-14 15:02
good catch. if it is only a version problem we are not going to spend more time on this issue on our behalf so I will close this issue. If you come up with a fix we are happy to see a pull request :)

Thanks for reporting, though!

**Closed by markbangert** 2018-08-14 15:02 UTC
