### ISSUE TITLE
Ray tracing, voxel positions to index

### ISSUE THREAD

**Issue by rcorredorj** [e0404/matRad#25] opened 2015-06-15 09:19 UTC
Hi,

In https://github.com/e0404/matRad/blob/12cdfc114ea5dc48b59ad624df33b00288a7b32a/matRad_siddonRayTracer.m#L198 : 
Why this line sets the voxel coords as j,i,k and not i,j,k ? I'm having problems at this point with images where dimX != dimY. This problem doesn't appear in your current datasets because dimX == dimY. If I set i,j,k to be consistent with the image dimensions (i.e. cubes{1}), then it works. Is there possibly a bug?

Thanks!

RaC

**Comment by rcorredorj** [comment] 2015-06-15 09:45
Or maybe the problem is in the previous lines to "Handle numerical instabilities at the borders". Should not be like this instead?

    % Handle numerical instabilities at the borders.
    i(i<=0) = 1; j(j<=0) = 1; k(k<=0) = 1;
    i(i>yNumPlanes-1) = yNumPlanes-1;
    j(j>xNumPlanes-1) = xNumPlanes-1;
    k(k>zNumPlanes-1) = zNumPlanes-1;

**Comment by markbangert** [comment] 2015-06-15 11:19
Hi RaC,

not much time to look into this issue today. Migth find time tonight or tomorrow morning at the latest. I dont think that the problem is in

% Handle numerical instabilities at the borders.
i(i<=0) = 1; j(j<=0) = 1; k(k<=0) = 1;
i(i>yNumPlanes-1) = yNumPlanes-1;
j(j>xNumPlanes-1) = xNumPlanes-1;
k(k>zNumPlanes-1) = zNumPlanes-1;

BTW: Note that we made substantial changes to the siddon ray tracer fixing some other bug already so may wanna update your code anyway.

I think there is something fishy with

% Convert to linear indices
ix = sub2ind(size(cubes{1}),j,i,k);

I just changed it to

% Convert to linear indices
ix = sub2ind(size(cubes{1}),i,j,k);

which surprisingly gives the same result for cubes where the x dimension equals the y dimension which leaves me even more puzzled. Will be in contact again shortly.

Mark

**Comment by rcorredorj** [comment] 2015-06-15 13:23
Hi Mark,

Thank you for your quick reply. It is indeed a strange problem, but now it seems it is working for me. 

I kept that part as it was, i.e.
    % Convert to linear indices
    ix = sub2ind(size(cubes{1}),j,i,k);
and I changed the handling at the boundaries as mentioned previously:
    i(i<=0) = 1; j(j<=0) = 1; k(k<=0) = 1;
    i(i>yNumPlanes-1) = yNumPlanes-1; % Notice that yNumPlanes goes with i
    j(j>xNumPlanes-1) = xNumPlanes-1; % Notice that xNumPlanes goes with j
    k(k>zNumPlanes-1) = zNumPlanes-1;
  
Creating a blank image with the dimensions of 'cubes' and setting a value of 1 to the voxels selected by the ray-tracing, generates a line correctly. Additionally, in order to deal with the problem non-squared images in the axial slices (i.e. dimX != dimY), I changed the meshgrid in the calcPhotonDose by a ndgrid allowing non-squared grids.

This commit in my matRad fork shows you both changes: https://github.com/rcorredorj/matRad/commit/6923efbf24fde451d903b9983b769e7cf33a11a6

BTW, just in the previous to commits I was trying to set the dimensions of the MLC, you can check if it does make sense to you.

Thanks again and I will keep checking your updates.

RaC

**Comment by markbangert** [comment] 2015-06-16 11:35
Hi RaC,

again thank you for informing us about this bug. The problem has to do with the fact that matlab's imagesc command will show the first array dimension along the vertical axis (intuitive y axis) and the second array dimension along the horizontal axis (intuitive x axis). As we wanted to have the other behavious (first dim along x, second dim along y) we usually interchange those dimensions in the code. In the ray tracer we forgot to do so.

We decided to fix this problem by changing line 67 to

% Save the numbers of planes.
[yNumPlanes, xNumPlanes, zNumPlanes] = size(cubes{1});

Your bug report also made me realize two more problems ydd night:

1. we had issues with anisotropic vixel resolutions in x and y direction
2. we had an offset of 0.5 voxels in the calculation of the geometrical distance of voxels from the virtual radiation source

However, this problem could be fixed by adjusing the functions matRad_calcParticleDose and matRad_calcPhotonDose in line 124 and 128 respectively

% generate meshgrid with CT position [mm]
[X_geo,Y_geo,Z_geo] = meshgrid(ct.resolution(1)*(1:size(ct.cube,2)),...
    ct.resolution(2)*(1:size(ct.cube,1)),ct.resolution(3)*(1:size(ct.cube,3)));

Besides that I tried to clean some of the code so it might make sense for you to update your source to the latest version at some point. The changes are already live in the dev and master branch.

Again thank you very much for pointing this out. It helped a lot to improve the ray tracing algorithm.

**Closed by markbangert** 2015-06-16 11:35 UTC

**Comment by rcorredorj** [comment] 2015-06-17 16:58
Thank you Mark.

I updated those changes and everything is working. Actually I was also wondering that there was possibly that little shift in the calculation but I was not completely sure of that. Nice to see that it was fixed. 

Just last question by now: Have you tried/checked this very little change for setting the MLC size as an additional parameter? [rcorredorj@6923efb](https://github.com/rcorredorj/matRad/commit/78f86002cafe8f9e332f67f41723a2dffb3bf62d) Does it make sense to you?

Thank you for replying all these questions and the ones you answered me via email. In my opinion, it's more dynamic, interactive, traceable and easy-to-share to post questions directly here than sending the email to the address in the Contact page, however it's only my point of view.

Regards,

RaC

**Comment by markbangert** [comment] 2015-06-18 07:27
Hi RaC,

I totally agree. For interactions regarding the code, gitHub provides the way better interface so I encourage you to also do so in the future. This helps a lot with the development. Thanks a lot!

Regarding the MLC Size: I had a look at your suggested changes in matRadGUI.m. I think it makes sense to include hardware information at some point but we are still discussing ways how to do that in the future. As this might be machine specific I would rather do this by setting a certain machine name which then triggers all changes further down the road (photon dose calc base data i.e. kernels and geometry, mlc size, constraints regarding leaf motion etc). Also with regard to a potential experimental verfication of our algorithms this is an important question. Anyway: we are still in the process of figuring that out and admittedly it is not one of our top priorities. Probably we rather start thinking about these issues for protons and carbon ions first.

**Comment by rcorredorj** [comment] 2015-06-18 08:05
Hi,

Yes, I fully agree. Those machine parameters were what I had in mind. However, in order to limit the beamlets for plans with big lesions it is probably a good way to tackle that problem quickly by only thresholding the rays on the beams eye view as I'm doing there. Probably it is only for the record if anyone has this requirement, but I agree it makes part of a bigger change in all matRad in the future.

Thanks
